# Copyright © 2022 Cask Data, Inc.
#  Licensed under the Apache License, Version 2.0 (the "License"); you may not
#  use this file except in compliance with the License. You may obtain a copy of
#  the License at
#  http://www.apache.org/licenses/LICENSE-2.0
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations under
#  the License.

name: Snapshot Maven Release Workflow

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

jobs:

  release-job:
    runs-on: k8-runner-e2e

    steps:

      - name: Get Secrets from GCP Secret Manager
        id: 'secrets'
        uses: 'google-github-actions/get-secretmanager-secrets@v0'
        with:
          secrets: |-
            SERVER_USERNAME:cdapio-github-builds/SERVER_USERNAME
            SERVER_TOKEN:cdapio-github-builds/SERVER_TOKEN
            MAVEN_GPG_PASSPHRASE:cdapio-github-builds/MAVEN_GPG_PASSPHRASE

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.ref }}

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven
        run: mvn -B package --file pom.xml
        env:
          MAVEN_OPTS: '-Xmx3200m'

      - name: Set up Apache Maven Central
        uses: actions/setup-java@v1
        with: # running setup-java again overwrites the settings.xml
          java-version: 1.8
          server-id: ossrh
          server-username: SERVER_USERNAME
          server-password: SERVER_PASSWORD
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Publish to Apache Maven Central
        run: mvn -DskipTests clean deploy -Dgpg.passphrase=$MAVEN_GPG_PASSPHRASE
        env:
          SERVER_USERNAME: ${{ steps.secrets.outputs.SERVER_USERNAME }}
          SERVER_PASSWORD: ${{ steps.secrets.outputs.SERVER_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ steps.secrets.outputs.MAVEN_GPG_PASSPHRASE }}
          MAVEN_OPTS: '-Xmx3200m'

